### ISSUE TITLE
use "state-sync" to get up-to-date

### ISSUE THREAD

**Issue by boz** [ovrclk/akash-on-akash#3]
With the new state sync feature, nodes don't have to replay every block from genesis.  It's a great feature to use for these nodes.

https://docs.tendermint.com/master/nodes/state-sync.html

I think that if we have this that we can actually do akash-on-akash in testnet.

**Comment by hydrogen18** [comment]
Should be taken care of in the linked PR, talked to Josh about turning on snapshots in some existing nodes so we can support this in the edgnet
